version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=ecareer_guidance
      - DB_USER=root
      - DB_PASS=password
    depends_on:
      - db
    volumes:
      - ./api:/var/www/html/api
      - ./public_html:/var/www/html/public_html

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecareer_guidance
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: 