version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=ecareer_guidance
      - DB_USER=postgres
      - DB_PASS=password
      - DB_PORT=5432
      - APP_ENV=local
    depends_on:
      - db
    volumes:
      - ./api:/var/www/html/api
      - ./public_html:/var/www/html/public_html

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ecareer_guidance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: 