services:
  - type: web
    name: ecareerguide-backend
    env: php
    buildCommand: composer install
    startCommand: vendor/bin/heroku-php-apache2 public_html/
    envVars:
      - key: PHP_VERSION
        value: 8.1
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false 